title: SpeechBrain
description: SpeechBrain is a speech toolkit fully based on PyTorch.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
logo: https://speechbrain.github.io/assets/logo.png
